name: External Contribution Notify

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: praetorian-inc/external-contrib-action@v1
        with:
          linear-team-id: "43502f93-0130-4cad-b35c-601bc4cc19a0"
          slack-channel-id: "C0A90QPJ55G"
          linear-assignee-id: "c0dd3407-3707-42f2-9a4c-c705c01e8487"
          linear-parent-issue-id: "e97ea7d9-219b-453a-bb2f-7a818dd6d4f6"
        env:
          ORG_MEMBER_CHECK_PAT: ${{ secrets.ORG_MEMBER_CHECK_PAT }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
